// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'app_widget.dart';

List<RouteEntity> get routes => [
  RouteEntity(key: '/home', uri: Uri.parse('/home'), routeBuilder: b0Builder),
  RouteEntity(
    key: '/auth/register',
    uri: Uri.parse('/auth/register'),
    routeBuilder: b1Builder,
  ),
  RouteEntity(
    key: '/auth/login',
    uri: Uri.parse('/auth/login'),
    routeBuilder: b2Builder,
  ),
  RouteEntity(
    key: '/splash',
    uri: Uri.parse('/splash'),
    routeBuilder: b3Builder,
  ),
];

const routePaths = (
  path: '/',
  home: '/home',
  auth: (path: '/auth', register: '/auth/register', login: '/auth/login'),
  splash: '/splash',
);
