version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: todo_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sq
      
  # todo_go:
  #   build:
  #     context: ../backend/todo_go_fiber
  #     dockerfile: Dockerfile
  #   container_name: todo_go
  #   restart: always
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ../backend/.env
  #   volumes:
  #     - ../backend/.env:/app/.env
  #   working_dir: /app

  todo_java:
    build:
      context: ../backend/todo_java_spring
    container_name: todo_java
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - ../backend/.env
    volumes:
      - ../backend/.env:/app/.env
    working_dir: /app

volumes:
  pgdata:
